DELETE
FROM EGOV_IAM_PERMISSION_DEFINITION
WHERE TRUE;
DELETE
FROM EGOV_IAM_ROLE_MEMBERSHIP
WHERE TRUE;

-- role membership for user that has access to the book as he created it
INSERT INTO EGOV_IAM_ROLE_MEMBERSHIP(ID, USERID, ROLEID, VALID_FROM, VALID_TO)
VALUES (1, 42, (SELECT EGOV_IAM_ROLE.ID FROM EGOV_IAM_ROLE WHERE ROLE_NAME = 'DEMO_ROLE'), '2000-01-01', '2050-01-01');

-- role membership for user that has no access to the book
INSERT INTO EGOV_IAM_ROLE_MEMBERSHIP(ID, USERID, ROLEID, VALID_FROM, VALID_TO)
VALUES (2, 17, (SELECT EGOV_IAM_ROLE.ID FROM EGOV_IAM_ROLE WHERE ROLE_NAME = 'DEMO_ROLE'), '2000-01-01', '2050-01-01');

-- allow read
INSERT INTO EGOV_IAM_PERMISSION_DEFINITION(ID, ROLEID, DESCRIPTION, ENTITY_TITLE, OPERATION, SQL_QUERY)
VALUES (1, (SELECT EGOV_IAM_ROLE.ID FROM EGOV_IAM_ROLE WHERE ROLE_NAME = 'DEMO_ROLE'), '', 'Book', 'READ', 'SELECT ID FROM BOOK WHERE URHEBER_ID = ?');

-- allow update
INSERT INTO EGOV_IAM_PERMISSION_DEFINITION(ID, ROLEID, DESCRIPTION, ENTITY_TITLE, OPERATION, SQL_QUERY)
VALUES (2, (SELECT EGOV_IAM_ROLE.ID FROM EGOV_IAM_ROLE WHERE ROLE_NAME = 'DEMO_ROLE'), '', 'Book', 'UPDATE', 'SELECT ID FROM BOOK WHERE URHEBER_ID = ?');

-- allow delete
INSERT INTO EGOV_IAM_PERMISSION_DEFINITION(ID, ROLEID, DESCRIPTION, ENTITY_TITLE, OPERATION, SQL_QUERY)
VALUES (3, (SELECT EGOV_IAM_ROLE.ID FROM EGOV_IAM_ROLE WHERE ROLE_NAME = 'DEMO_ROLE'), '', 'Book', 'DELETE', 'SELECT ID FROM BOOK WHERE URHEBER_ID = ?');