create table egov_mdm_record
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    code               varchar(200) not null ,
    vocabulary_code    varchar(200) not null ,
    language_code      varchar(20),
    long_name          varchar(2000),
    short_name         varchar(200),
    valid_from         TIMESTAMP WITHOUT TIME ZONE,
    valid_to           TIMESTAMP WITHOUT TIME ZONE,
    weight             integer,
    additional_content varchar(32000),
    created_by         varchar(255),
    modified_by        varchar(255),
    created_date       TIMESTAMP WITHOUT TIME ZONE,
    modified_date      TIMESTAMP WITHOUT TIME ZONE,
    archived           boolean not null default false,
    CONSTRAINT pk_egov_mdm_record PRIMARY KEY (id)
);

create index idx_egov_mdm_record_code on egov_mdm_record (code);

create index idx_egov_mdm_record_validity on egov_mdm_record (valid_from, valid_to) include (code);

create index idx_egov_mdm_record_language on egov_mdm_record (language_code);

create index idx_egov_mdm_record_weight on egov_mdm_record (weight);

create table egov_mdm_vocabulary
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    code                 varchar(200) not null unique,
    modifiable           boolean not null default true,
    sortable             boolean not null default true,
    name_validation_type varchar(20) default 'LONG_AND_SHORT_NAME'::character varying not null,
    created_by           varchar(255),
    modified_by          varchar(255),
    created_date         TIMESTAMP WITHOUT TIME ZONE,
    modified_date        TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_egov_mdm_vocabulary PRIMARY KEY (id)
);

create table egov_mdm_vocabulary_ln
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name           varchar(200),
    language_code  varchar(20) not null,
    description    varchar(2000),
    created_by     varchar(255),
    modified_by    varchar(255),
    created_date   TIMESTAMP WITHOUT TIME ZONE,
    modified_date  TIMESTAMP WITHOUT TIME ZONE,
    vocabularycode varchar(200),
    CONSTRAINT pk_egov_mdm_vocabulary_ln PRIMARY KEY (id)
);

create table egov_mdm_field_definition
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    code           varchar(200) not null,
    type           varchar(20),
    default_value  varchar(255),
    created_by     varchar(255),
    modified_by    varchar(255),
    created_date   TIMESTAMP WITHOUT TIME ZONE,
    modified_date  TIMESTAMP WITHOUT TIME ZONE,
    vocabularycode varchar(200),
    CONSTRAINT pk_egov_mdm_field_definition PRIMARY KEY (id)
);

create table egov_mdm_field_definition_ln
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name          varchar(200),
    language_code varchar(20),
    created_by    varchar(255),
    modified_by   varchar(255),
    created_date  TIMESTAMP WITHOUT TIME ZONE,
    modified_date TIMESTAMP WITHOUT TIME ZONE,
    fieldcode     varchar(200),
    CONSTRAINT pk_egov_mdm_field_definition_ln PRIMARY KEY (id)
);

create table egov_mdm_language_definition
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    language_code  varchar(20),
    created_by     varchar(255),
    modified_by    varchar(255),
    created_date   TIMESTAMP WITHOUT TIME ZONE,
    modified_date  TIMESTAMP WITHOUT TIME ZONE,
    vocabularycode varchar(200),
    CONSTRAINT pk_egov_mdm_language_definition PRIMARY KEY (id)
);

ALTER TABLE egov_mdm_field_definition
    ADD CONSTRAINT fk_egov_mdm_field_definition_on_vocabularycode FOREIGN KEY (vocabularycode) REFERENCES egov_mdm_vocabulary (code);

ALTER TABLE egov_mdm_language_definition
    ADD CONSTRAINT fk_egov_mdm_language_definition_on_vocabularycode FOREIGN KEY (vocabularycode) REFERENCES egov_mdm_vocabulary (code);

ALTER TABLE egov_mdm_vocabulary_ln
    ADD CONSTRAINT fk_egov_mdm_vocabulary_ln_on_vocabularycode FOREIGN KEY (vocabularycode) REFERENCES egov_mdm_vocabulary (code);

CREATE SEQUENCE IF NOT EXISTS egov_mdm_record_seq INCREMENT BY 50 MINVALUE 0 MAXVALUE 9223372036854775807 START 1;
CREATE SEQUENCE IF NOT EXISTS egov_mdm_vocabulary_seq INCREMENT BY 50 MINVALUE 0 MAXVALUE 9223372036854775807 START 1;
CREATE SEQUENCE IF NOT EXISTS egov_mdm_vocabulary_ln_seq INCREMENT BY 50 MINVALUE 0 MAXVALUE 9223372036854775807 START 1;
CREATE SEQUENCE IF NOT EXISTS egov_mdm_field_definition_seq INCREMENT BY 50 MINVALUE 0 MAXVALUE 9223372036854775807 START 1;
CREATE SEQUENCE IF NOT EXISTS egov_mdm_field_definition_ln_seq INCREMENT BY 50 MINVALUE 0 MAXVALUE 9223372036854775807 START 1;
CREATE SEQUENCE IF NOT EXISTS egov_mdm_language_definition_seq INCREMENT BY 50 MINVALUE 0 MAXVALUE 9223372036854775807 START 1;
