CREATE TABLE egov_cmd_command
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_by            VARCHAR(255),
    modified_by           VARCHAR(255),
    created_date          TIMESTAMP WITHOUT TIME ZONE,
    modified_date         TIMESTAMP WITHOUT TIME ZONE,
    action                VARCHAR(255),
    aggregate_name        VARCHAR(255),
    command_value         VARCHAR(8000),
    version               VARCHAR(255),
    execution_plan        VARCHAR(255),
    executing_user_id     VARCHAR(255),
    aggregate_id          BIGINT,
    domain                VARCHAR(255),
    status                VARCHAR(255),
    info                  VARCHAR(255),
    error                 VARCHAR(32000),
    absolute_request_path TEXT,
    parameters            VARCHAR(4000),
    exception_id          VARCHAR(255),
    parentid              BIGINT,
    CONSTRAINT pk_egov_cmd_command PRIMARY KEY (id)
);

CREATE TABLE egov_iam_condition
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    action                 VARCHAR(255),
    allowed_for_all_roles  BOOLEAN,
    allowed_for_all_states BOOLEAN,
    rulesetid              BIGINT,
    CONSTRAINT pk_egov_iam_condition PRIMARY KEY (id)
);

CREATE TABLE egov_iam_condition_allowed_for_role
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    roleid      BIGINT,
    conditionid BIGINT,
    CONSTRAINT pk_egov_iam_condition_allowed_for_role PRIMARY KEY (id)
);

CREATE TABLE egov_iam_condition_allowed_for_state
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    state       VARCHAR(255),
    conditionid BIGINT,
    CONSTRAINT pk_egov_iam_condition_allowed_for_state PRIMARY KEY (id)
);

CREATE TABLE egov_iam_permission_definition
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description  VARCHAR(255),
    entity_title VARCHAR(255),
    sql_query TEXT,
    operation    VARCHAR(255),
    roleid       BIGINT,
    CONSTRAINT pk_egov_iam_permission_definition PRIMARY KEY (id)
);

CREATE TABLE egov_iam_role
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    role_name VARCHAR(255),
    CONSTRAINT pk_egov_iam_role PRIMARY KEY (id)
);

CREATE TABLE egov_iam_role_ln
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    language_id VARCHAR(255),
    description VARCHAR(255),
    roleid      BIGINT,
    CONSTRAINT pk_egov_iam_role_ln PRIMARY KEY (id)
);

CREATE TABLE egov_iam_role_membership
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    userid     VARCHAR(255),
    valid_from TIMESTAMP WITHOUT TIME ZONE,
    valid_to   TIMESTAMP WITHOUT TIME ZONE,
    roleid     BIGINT,
    CONSTRAINT pk_egov_iam_role_membership PRIMARY KEY (id)
);

CREATE TABLE egov_iam_rule_set
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description       VARCHAR(255),
    validation_entity VARCHAR(8000),
    rule_set_code     VARCHAR(255),
    category          VARCHAR(255),
    rule_set_priority INTEGER,
    CONSTRAINT pk_egov_iam_rule_set PRIMARY KEY (id)
);

CREATE TABLE egov_per_aa_health_check_test
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_by    VARCHAR(255),
    modified_by   VARCHAR(255),
    created_date  TIMESTAMP WITHOUT TIME ZONE,
    modified_date TIMESTAMP WITHOUT TIME ZONE,
    text          VARCHAR(255),
    CONSTRAINT pk_egov_per_aa_healthchecktest PRIMARY KEY (id)
);

CREATE TABLE egov_per_aa_info
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_by    VARCHAR(255),
    modified_by   VARCHAR(255),
    created_date  TIMESTAMP WITHOUT TIME ZONE,
    modified_date TIMESTAMP WITHOUT TIME ZONE,
    text          VARCHAR(255),
    CONSTRAINT pk_egov_per_aa_info PRIMARY KEY (id)
);

CREATE TABLE egov_per_aa_row_count
(
    table_name VARCHAR(255) NOT NULL,
    row_count  INTEGER,
    CONSTRAINT pk_egov_per_aa_rowcount PRIMARY KEY (table_name)
);

ALTER TABLE egov_iam_condition
    ADD CONSTRAINT uc_egov_iam_condition_rulesetid UNIQUE (rulesetid);

ALTER TABLE egov_cmd_command
    ADD CONSTRAINT FK_EGOV_CMD_COMMAND_ON_PARENTID FOREIGN KEY (parentid) REFERENCES egov_cmd_command (id);

ALTER TABLE egov_iam_condition_allowed_for_role
    ADD CONSTRAINT FK_EGOV_IAM_CONDITION_ALLOWED_FOR_ROLE_ON_CONDITIONID FOREIGN KEY (conditionid) REFERENCES egov_iam_condition (id);

ALTER TABLE egov_iam_condition_allowed_for_role
    ADD CONSTRAINT FK_EGOV_IAM_CONDITION_ALLOWED_FOR_ROLE_ON_ROLEID FOREIGN KEY (roleid) REFERENCES egov_iam_role (id);

ALTER TABLE egov_iam_condition_allowed_for_state
    ADD CONSTRAINT FK_EGOV_IAM_CONDITION_ALLOWED_FOR_STATE_ON_CONDITIONID FOREIGN KEY (conditionid) REFERENCES egov_iam_condition (id);

ALTER TABLE egov_iam_condition
    ADD CONSTRAINT FK_EGOV_IAM_CONDITION_ON_RULESETID FOREIGN KEY (rulesetid) REFERENCES egov_iam_rule_set (id);

ALTER TABLE egov_iam_permission_definition
    ADD CONSTRAINT FK_EGOV_IAM_PERMISSION_DEFINITION_ON_ROLEID FOREIGN KEY (roleid) REFERENCES egov_iam_role (id);

ALTER TABLE egov_iam_role_ln
    ADD CONSTRAINT FK_EGOV_IAM_ROLE_LN_ON_ROLEID FOREIGN KEY (roleid) REFERENCES egov_iam_role (id);

ALTER TABLE egov_iam_role_membership
    ADD CONSTRAINT FK_EGOV_IAM_ROLE_MEMBERSHIP_ON_ROLEID FOREIGN KEY (roleid) REFERENCES egov_iam_role (id);