DELETE FROM egov_iam_condition_allowed_for_role;
DELETE FROM egov_iam_condition_allowed_for_state;
DELETE FROM egov_iam_condition;
DELETE FROM egov_iam_rule_set;
INSERT INTO egov_iam_role (id, role_name) SELECT 6178461400000000, 'MASTER_DATA_ADMIN' WHERE NOT EXISTS (SELECT 1 FROM egov_iam_role WHERE egov_iam_role.role_name = 'MASTER_DATA_ADMIN');
INSERT INTO egov_iam_role (id, role_name) SELECT 6178461400000001, 'MASTER_DATA_ADMIN' WHERE NOT EXISTS (SELECT 1 FROM egov_iam_role WHERE egov_iam_role.role_name = 'MASTER_DATA_ADMIN');
INSERT INTO egov_iam_role (id, role_name) SELECT 6178461400000002, 'MASTER_DATA_ADMIN' WHERE NOT EXISTS (SELECT 1 FROM egov_iam_role WHERE egov_iam_role.role_name = 'MASTER_DATA_ADMIN');
INSERT INTO egov_iam_role (id, role_name) SELECT 6178461400000003, 'MASTER_DATA_ADMIN' WHERE NOT EXISTS (SELECT 1 FROM egov_iam_role WHERE egov_iam_role.role_name = 'MASTER_DATA_ADMIN');
INSERT INTO egov_iam_role (id, role_name) SELECT 6178461400000004, 'MASTER_DATA_ADMIN' WHERE NOT EXISTS (SELECT 1 FROM egov_iam_role WHERE egov_iam_role.role_name = 'MASTER_DATA_ADMIN');
INSERT INTO egov_iam_role (id, role_name) SELECT 6178461400000005, 'MASTER_DATA_ADMIN' WHERE NOT EXISTS (SELECT 1 FROM egov_iam_role WHERE egov_iam_role.role_name = 'MASTER_DATA_ADMIN');
-- Class Name : ch.ti8m.egov.mdm.api.dto.DeleteMasterDataEntryDto
INSERT INTO egov_iam_rule_set (id, rule_set_code, description, category, rule_set_priority, validation_entity) VALUES (6178461400000006, 'DELETE_MASTER_DATA_ENTRY', 'Delete Master Data Entry', 'Master Data', 0, '{"fields":{},"type":"object","subtype":null,"validation":null}');
INSERT INTO egov_iam_condition (id, action, allowed_for_all_roles, allowed_for_all_states, rulesetid) VALUES (6178461400000007, 'MasterDataApplicationService_DELETE_MASTER_DATA_ENTRY', FALSE, TRUE, (SELECT id FROM egov_iam_rule_set WHERE rule_set_code = 'DELETE_MASTER_DATA_ENTRY'));
INSERT INTO egov_iam_condition_allowed_for_role (id, roleid, conditionid) VALUES (6178461400000008, (SELECT id FROM egov_iam_role WHERE role_name = 'MASTER_DATA_ADMIN'), (SELECT id FROM egov_iam_condition WHERE rulesetid = (SELECT id FROM egov_iam_rule_set WHERE rule_set_code = 'DELETE_MASTER_DATA_ENTRY')));
-- Class Name : ch.ti8m.egov.mdm.api.dto.DeleteVocabularyDto
INSERT INTO egov_iam_rule_set (id, rule_set_code, description, category, rule_set_priority, validation_entity) VALUES (6178461400000009, 'DELETE_VOCABULARY', 'Delete Master Data Vocabulary', 'Master Data', 0, '{"fields":{},"type":"object","subtype":null,"validation":null}');
INSERT INTO egov_iam_condition (id, action, allowed_for_all_roles, allowed_for_all_states, rulesetid) VALUES (6178461400000010, 'MasterDataApplicationService_DELETE_VOCABULARY', FALSE, TRUE, (SELECT id FROM egov_iam_rule_set WHERE rule_set_code = 'DELETE_VOCABULARY'));
INSERT INTO egov_iam_condition_allowed_for_role (id, roleid, conditionid) VALUES (6178461400000011, (SELECT id FROM egov_iam_role WHERE role_name = 'MASTER_DATA_ADMIN'), (SELECT id FROM egov_iam_condition WHERE rulesetid = (SELECT id FROM egov_iam_rule_set WHERE rule_set_code = 'DELETE_VOCABULARY')));
-- Class Name : ch.ti8m.egov.mdm.api.dto.CreateVocabularyDto
INSERT INTO egov_iam_rule_set (id, rule_set_code, description, category, rule_set_priority, validation_entity) VALUES (6178461400000012, 'CREATE_VOCABULARY', 'Create Master Data Vocabulary', 'Master Data', 0, '{"fields":{"code":{"fields":{},"type":"string","subtype":null,"validation":null},"languages":{"fields":{"languageCode":{"fields":{},"type":"string","subtype":null,"validation":null}},"type":"list","subtype":"object","validation":null},"localizations":{"fields":{"name":{"fields":{},"type":"string","subtype":null,"validation":null},"description":{"fields":{},"type":"string","subtype":null,"validation":null},"languageCode":{"fields":{},"type":"string","subtype":null,"validation":null}},"type":"list","subtype":"object","validation":null},"sortable":{"fields":{},"type":"bool","subtype":null,"validation":null},"modifiable":{"fields":{},"type":"bool","subtype":null,"validation":null},"fields":{"fields":{"code":{"fields":{},"type":"string","subtype":null,"validation":null},"localizations":{"fields":{"name":{"fields":{},"type":"string","subtype":null,"validation":null},"languageCode":{"fields":{},"type":"string","subtype":null,"validation":null}},"type":"list","subtype":"object","validation":null},"defaultValue":{"fields":{},"type":"string","subtype":null,"validation":null},"type":{"fields":{},"type":"string","subtype":null,"validation":null}},"type":"list","subtype":"object","validation":null},"nameValidationType":{"fields":{},"type":"any","subtype":null,"validation":null}},"type":"object","subtype":null,"validation":null}');
INSERT INTO egov_iam_condition (id, action, allowed_for_all_roles, allowed_for_all_states, rulesetid) VALUES (6178461400000013, 'MasterDataApplicationService_CREATE_VOCABULARY', FALSE, TRUE, (SELECT id FROM egov_iam_rule_set WHERE rule_set_code = 'CREATE_VOCABULARY'));
INSERT INTO egov_iam_condition_allowed_for_role (id, roleid, conditionid) VALUES (6178461400000014, (SELECT id FROM egov_iam_role WHERE role_name = 'MASTER_DATA_ADMIN'), (SELECT id FROM egov_iam_condition WHERE rulesetid = (SELECT id FROM egov_iam_rule_set WHERE rule_set_code = 'CREATE_VOCABULARY')));
-- Class Name : ch.ti8m.egov.mdm.api.dto.GetMasterDataEntryDto
INSERT INTO egov_iam_rule_set (id, rule_set_code, description, category, rule_set_priority, validation_entity) VALUES (6178461400000015, 'GET_VALID_MASTER_DATA_ENTRY', 'Get Master Data Entry', 'Master Data', 0, '{"fields":{"code":{"fields":{},"type":"string","subtype":null,"validation":null},"vocabularyCode":{"fields":{},"type":"string","subtype":null,"validation":null},"weight":{"fields":{},"type":"int","subtype":null,"validation":null},"validFrom":{"fields":{},"type":"localdatetime","subtype":null,"validation":null},"languageCode":{"fields":{},"type":"string","subtype":null,"validation":null},"shortName":{"fields":{},"type":"string","subtype":null,"validation":null},"validTo":{"fields":{},"type":"localdatetime","subtype":null,"validation":null},"longName":{"fields":{},"type":"string","subtype":null,"validation":null}},"type":"object","subtype":null,"validation":null}');
INSERT INTO egov_iam_condition (id, action, allowed_for_all_roles, allowed_for_all_states, rulesetid) VALUES (6178461400000016, 'MasterDataApplicationService_GET_VALID_MASTER_DATA_ENTRY', TRUE, TRUE, (SELECT id FROM egov_iam_rule_set WHERE rule_set_code = 'GET_VALID_MASTER_DATA_ENTRY'));
-- Class Name : ch.ti8m.egov.mdm.api.dto.UpdateMasterDataEntryDto
INSERT INTO egov_iam_rule_set (id, rule_set_code, description, category, rule_set_priority, validation_entity) VALUES (6178461400000017, 'UPDATE_MASTER_DATA_ENTRY', 'Update Master Data Entry', 'Master Data', 0, '{"fields":{"additionalContent":{"fields":{},"type":"object","subtype":null,"validation":null},"weight":{"fields":{},"type":"int","subtype":null,"validation":null},"validFrom":{"fields":{},"type":"localdatetime","subtype":null,"validation":null},"shortName":{"fields":{},"type":"string","subtype":null,"validation":null},"validTo":{"fields":{},"type":"localdatetime","subtype":null,"validation":null},"longName":{"fields":{},"type":"string","subtype":null,"validation":null}},"type":"object","subtype":null,"validation":null}');
INSERT INTO egov_iam_condition (id, action, allowed_for_all_roles, allowed_for_all_states, rulesetid) VALUES (6178461400000018, 'MasterDataApplicationService_UPDATE_MASTER_DATA_ENTRY', FALSE, TRUE, (SELECT id FROM egov_iam_rule_set WHERE rule_set_code = 'UPDATE_MASTER_DATA_ENTRY'));
INSERT INTO egov_iam_condition_allowed_for_role (id, roleid, conditionid) VALUES (6178461400000019, (SELECT id FROM egov_iam_role WHERE role_name = 'MASTER_DATA_ADMIN'), (SELECT id FROM egov_iam_condition WHERE rulesetid = (SELECT id FROM egov_iam_rule_set WHERE rule_set_code = 'UPDATE_MASTER_DATA_ENTRY')));
-- Class Name : ch.ti8m.egov.mdm.api.dto.GetMasterDataEntriesDto
INSERT INTO egov_iam_rule_set (id, rule_set_code, description, category, rule_set_priority, validation_entity) VALUES (6178461400000020, 'GET_VALID_MASTER_DATA_ENTRIES', 'Get Master Data Entries', 'Master Data', 0, '{"fields":{"entries":{"fields":{"code":{"fields":{},"type":"string","subtype":null,"validation":null},"vocabularyCode":{"fields":{},"type":"string","subtype":null,"validation":null},"weight":{"fields":{},"type":"int","subtype":null,"validation":null},"validFrom":{"fields":{},"type":"localdatetime","subtype":null,"validation":null},"languageCode":{"fields":{},"type":"string","subtype":null,"validation":null},"shortName":{"fields":{},"type":"string","subtype":null,"validation":null},"validTo":{"fields":{},"type":"localdatetime","subtype":null,"validation":null},"longName":{"fields":{},"type":"string","subtype":null,"validation":null}},"type":"list","subtype":"object","validation":null}},"type":"object","subtype":null,"validation":null}');
INSERT INTO egov_iam_condition (id, action, allowed_for_all_roles, allowed_for_all_states, rulesetid) VALUES (6178461400000021, 'MasterDataApplicationService_GET_VALID_MASTER_DATA_ENTRIES', TRUE, TRUE, (SELECT id FROM egov_iam_rule_set WHERE rule_set_code = 'GET_VALID_MASTER_DATA_ENTRIES'));
-- Class Name : ch.ti8m.egov.mdm.api.dto.CreateMasterDataEntryDto
INSERT INTO egov_iam_rule_set (id, rule_set_code, description, category, rule_set_priority, validation_entity) VALUES (6178461400000022, 'CREATE_MASTER_DATA_ENTRY', 'Create Master Data Entry', 'Master Data', 0, '{"fields":{"code":{"fields":{},"type":"string","subtype":null,"validation":null},"vocabularyCode":{"fields":{},"type":"string","subtype":null,"validation":null},"additionalContent":{"fields":{},"type":"object","subtype":null,"validation":null},"weight":{"fields":{},"type":"int","subtype":null,"validation":null},"validFrom":{"fields":{},"type":"localdatetime","subtype":null,"validation":null},"languageCode":{"fields":{},"type":"string","subtype":null,"validation":null},"shortName":{"fields":{},"type":"string","subtype":null,"validation":null},"validTo":{"fields":{},"type":"localdatetime","subtype":null,"validation":null},"longName":{"fields":{},"type":"string","subtype":null,"validation":null}},"type":"object","subtype":null,"validation":null}');
INSERT INTO egov_iam_condition (id, action, allowed_for_all_roles, allowed_for_all_states, rulesetid) VALUES (6178461400000023, 'MasterDataApplicationService_CREATE_MASTER_DATA_ENTRY', FALSE, TRUE, (SELECT id FROM egov_iam_rule_set WHERE rule_set_code = 'CREATE_MASTER_DATA_ENTRY'));
INSERT INTO egov_iam_condition_allowed_for_role (id, roleid, conditionid) VALUES (6178461400000024, (SELECT id FROM egov_iam_role WHERE role_name = 'MASTER_DATA_ADMIN'), (SELECT id FROM egov_iam_condition WHERE rulesetid = (SELECT id FROM egov_iam_rule_set WHERE rule_set_code = 'CREATE_MASTER_DATA_ENTRY')));
-- Class Name : ch.ti8m.egov.mdm.api.dto.GetVocabulariesDto
INSERT INTO egov_iam_rule_set (id, rule_set_code, description, category, rule_set_priority, validation_entity) VALUES (6178461400000025, 'GET_VOCABULARIES', 'Get Master Data Vocabularies', 'Master Data', 0, '{"fields":{"vocabularies":{"fields":{"code":{"fields":{},"type":"string","subtype":null,"validation":null},"languages":{"fields":{"languageCode":{"fields":{},"type":"string","subtype":null,"validation":null}},"type":"list","subtype":"object","validation":null},"localizations":{"fields":{"name":{"fields":{},"type":"string","subtype":null,"validation":null},"description":{"fields":{},"type":"string","subtype":null,"validation":null},"languageCode":{"fields":{},"type":"string","subtype":null,"validation":null}},"type":"list","subtype":"object","validation":null},"sortable":{"fields":{},"type":"bool","subtype":null,"validation":null},"modifiable":{"fields":{},"type":"bool","subtype":null,"validation":null},"fields":{"fields":{"code":{"fields":{},"type":"string","subtype":null,"validation":null},"localizations":{"fields":{"name":{"fields":{},"type":"string","subtype":null,"validation":null},"languageCode":{"fields":{},"type":"string","subtype":null,"validation":null}},"type":"list","subtype":"object","validation":null},"defaultValue":{"fields":{},"type":"string","subtype":null,"validation":null},"type":{"fields":{},"type":"string","subtype":null,"validation":null}},"type":"list","subtype":"object","validation":null},"nameValidationType":{"fields":{},"type":"any","subtype":null,"validation":null}},"type":"list","subtype":"object","validation":null}},"type":"object","subtype":null,"validation":null}');
INSERT INTO egov_iam_condition (id, action, allowed_for_all_roles, allowed_for_all_states, rulesetid) VALUES (6178461400000026, 'MasterDataApplicationService_GET_VOCABULARIES', TRUE, TRUE, (SELECT id FROM egov_iam_rule_set WHERE rule_set_code = 'GET_VOCABULARIES'));
-- Class Name : ch.ti8m.egov.mdm.api.dto.UpdateVocabularyDto
INSERT INTO egov_iam_rule_set (id, rule_set_code, description, category, rule_set_priority, validation_entity) VALUES (6178461400000027, 'UPDATE_VOCABULARY', 'Update Master Data Vocabulary', 'Master Data', 0, '{"fields":{"languages":{"fields":{"languageCode":{"fields":{},"type":"string","subtype":null,"validation":null}},"type":"list","subtype":"object","validation":null},"localizations":{"fields":{"name":{"fields":{},"type":"string","subtype":null,"validation":null},"description":{"fields":{},"type":"string","subtype":null,"validation":null},"languageCode":{"fields":{},"type":"string","subtype":null,"validation":null}},"type":"list","subtype":"object","validation":null},"sortable":{"fields":{},"type":"bool","subtype":null,"validation":null},"modifiable":{"fields":{},"type":"bool","subtype":null,"validation":null},"fields":{"fields":{"code":{"fields":{},"type":"string","subtype":null,"validation":null},"localizations":{"fields":{"name":{"fields":{},"type":"string","subtype":null,"validation":null},"languageCode":{"fields":{},"type":"string","subtype":null,"validation":null}},"type":"list","subtype":"object","validation":null},"defaultValue":{"fields":{},"type":"string","subtype":null,"validation":null},"type":{"fields":{},"type":"string","subtype":null,"validation":null}},"type":"list","subtype":"object","validation":null},"nameValidationType":{"fields":{},"type":"any","subtype":null,"validation":null}},"type":"object","subtype":null,"validation":null}');
INSERT INTO egov_iam_condition (id, action, allowed_for_all_roles, allowed_for_all_states, rulesetid) VALUES (6178461400000028, 'MasterDataApplicationService_UPDATE_VOCABULARY', FALSE, TRUE, (SELECT id FROM egov_iam_rule_set WHERE rule_set_code = 'UPDATE_VOCABULARY'));
INSERT INTO egov_iam_condition_allowed_for_role (id, roleid, conditionid) VALUES (6178461400000029, (SELECT id FROM egov_iam_role WHERE role_name = 'MASTER_DATA_ADMIN'), (SELECT id FROM egov_iam_condition WHERE rulesetid = (SELECT id FROM egov_iam_rule_set WHERE rule_set_code = 'UPDATE_VOCABULARY')));
-- Class Name : ch.ti8m.egov.mdm.api.dto.GetVocabularyDto
INSERT INTO egov_iam_rule_set (id, rule_set_code, description, category, rule_set_priority, validation_entity) VALUES (6178461400000030, 'GET_VOCABULARY', 'Get Master Data Vocabulary', 'Master Data', 0, '{"fields":{"code":{"fields":{},"type":"string","subtype":null,"validation":null},"languages":{"fields":{"languageCode":{"fields":{},"type":"string","subtype":null,"validation":null}},"type":"list","subtype":"object","validation":null},"localizations":{"fields":{"name":{"fields":{},"type":"string","subtype":null,"validation":null},"description":{"fields":{},"type":"string","subtype":null,"validation":null},"languageCode":{"fields":{},"type":"string","subtype":null,"validation":null}},"type":"list","subtype":"object","validation":null},"sortable":{"fields":{},"type":"bool","subtype":null,"validation":null},"modifiable":{"fields":{},"type":"bool","subtype":null,"validation":null},"fields":{"fields":{"code":{"fields":{},"type":"string","subtype":null,"validation":null},"localizations":{"fields":{"name":{"fields":{},"type":"string","subtype":null,"validation":null},"languageCode":{"fields":{},"type":"string","subtype":null,"validation":null}},"type":"list","subtype":"object","validation":null},"defaultValue":{"fields":{},"type":"string","subtype":null,"validation":null},"type":{"fields":{},"type":"string","subtype":null,"validation":null}},"type":"list","subtype":"object","validation":null},"nameValidationType":{"fields":{},"type":"any","subtype":null,"validation":null}},"type":"object","subtype":null,"validation":null}');
INSERT INTO egov_iam_condition (id, action, allowed_for_all_roles, allowed_for_all_states, rulesetid) VALUES (6178461400000031, 'MasterDataApplicationService_GET_VOCABULARY', TRUE, TRUE, (SELECT id FROM egov_iam_rule_set WHERE rule_set_code = 'GET_VOCABULARY'));