DELETE
FROM EGOV_IAM_PERMISSION_DEFINITION
WHERE TRUE;
DELETE
FROM EGOV_IAM_ROLE_MEMBERSHIP
WHERE TRUE;

-- role membership for user 42
INSERT INTO EGOV_IAM_ROLE_MEMBERSHIP(ID, USERID, ROLEID, VALID_FROM, VALID_TO)
VALUES (1, 42, (SELECT EGOV_IAM_ROLE.ID FROM EGOV_IAM_ROLE WHERE ROLE_NAME = 'MASTER_DATA_ADMIN'), '2000-01-01', '2050-01-01');

-- allow read for Vocabulary
INSERT INTO EGOV_IAM_PERMISSION_DEFINITION(ID, ROLEID, DESCRIPTION, ENTITY_TITLE, OPERATION, SQL_QUERY)
VALUES (1, (SELECT EGOV_IAM_ROLE.ID FROM EGOV_IAM_ROLE WHERE ROLE_NAME = 'MASTER_DATA_ADMIN'), '', 'Vocabulary', 'READ', 'SELECT ID FROM EGOV_MDM_VOCABULARY');

-- allow update for Vocabulary
INSERT INTO EGOV_IAM_PERMISSION_DEFINITION(ID, ROLEID, DESCRIPTION, ENTITY_TITLE, OPERATION, SQL_QUERY)
VALUES (2, (SELECT EGOV_IAM_ROLE.ID FROM EGOV_IAM_ROLE WHERE ROLE_NAME = 'MASTER_DATA_ADMIN'), '', 'Vocabulary', 'UPDATE', 'SELECT ID FROM EGOV_MDM_VOCABULARY');

-- allow delete for Vocabulary
INSERT INTO EGOV_IAM_PERMISSION_DEFINITION(ID, ROLEID, DESCRIPTION, ENTITY_TITLE, OPERATION, SQL_QUERY)
VALUES (3, (SELECT EGOV_IAM_ROLE.ID FROM EGOV_IAM_ROLE WHERE ROLE_NAME = 'MASTER_DATA_ADMIN'), '', 'Vocabulary', 'DELETE', 'SELECT ID FROM EGOV_MDM_VOCABULARY');

-- allow read for MasterDataGenericEntity
INSERT INTO EGOV_IAM_PERMISSION_DEFINITION(ID, ROLEID, DESCRIPTION, ENTITY_TITLE, OPERATION, SQL_QUERY)
VALUES (4, (SELECT EGOV_IAM_ROLE.ID FROM EGOV_IAM_ROLE WHERE ROLE_NAME = 'MASTER_DATA_ADMIN'), '', 'MasterDataGenericEntity', 'READ', 'SELECT ID FROM EGOV_MDM_RECORD');

-- allow update for MasterDataGenericEntity
INSERT INTO EGOV_IAM_PERMISSION_DEFINITION(ID, ROLEID, DESCRIPTION, ENTITY_TITLE, OPERATION, SQL_QUERY)
VALUES (5, (SELECT EGOV_IAM_ROLE.ID FROM EGOV_IAM_ROLE WHERE ROLE_NAME = 'MASTER_DATA_ADMIN'), '', 'MasterDataGenericEntity', 'UPDATE', 'SELECT ID FROM EGOV_MDM_RECORD');

-- allow delete for MasterDataGenericEntity
INSERT INTO EGOV_IAM_PERMISSION_DEFINITION(ID, ROLEID, DESCRIPTION, ENTITY_TITLE, OPERATION, SQL_QUERY)
VALUES (6, (SELECT EGOV_IAM_ROLE.ID FROM EGOV_IAM_ROLE WHERE ROLE_NAME = 'MASTER_DATA_ADMIN'), '', 'MasterDataGenericEntity', 'DELETE', 'SELECT ID FROM EGOV_MDM_RECORD');
